### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/renraku#22]
- [x] :fire: smarter error handling
  - probably have `ExposedError` or `PublicError`, which the user can extend to indicate that such errors can be safely exposed/published
  - maybe rename `exposeErrors` option to something like `exposeAllUnknownErrors`
- [ ] refactor to extract json-rpc batch handling for http/websocket into `s/comms/`
  - currently each transport does its own funky adhoc implementation
- [ ] test suites
- [x] postMessage
- [ ] allow force-notification remote-proxy invocations
  - eg, `remote.state.update[notification](data)`
  - also the types for notifications and settings are borked

**Comment by chase-moskal** [comment]
i think this crap is done
